/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSheetsRouteImport } from './routes/_authenticated/sheets'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedQueueRouteImport } from './routes/_authenticated/queue'
import { Route as AuthenticatedPagesRouteImport } from './routes/_authenticated/pages'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedGroupsRouteImport } from './routes/_authenticated/groups'
import { Route as AuthenticatedExtractRouteImport } from './routes/_authenticated/extract'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedComposerRouteImport } from './routes/_authenticated/composer'
import { Route as AuthenticatedCommentsRouteImport } from './routes/_authenticated/comments'
import { Route as ApiPublicDriveSplatRouteImport } from './routes/api/public/drive.$'
import { Route as ApiPublicCronSchedulerRouteImport } from './routes/api/public/cron/scheduler'
import { Route as ApiPublicCronRefreshTokensRouteImport } from './routes/api/public/cron/refresh-tokens'
import { Route as ApiPublicCronCaptureInsightsRouteImport } from './routes/api/public/cron/capture-insights'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSheetsRoute = AuthenticatedSheetsRouteImport.update({
  id: '/sheets',
  path: '/sheets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQueueRoute = AuthenticatedQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPagesRoute = AuthenticatedPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroupsRoute = AuthenticatedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExtractRoute = AuthenticatedExtractRouteImport.update({
  id: '/extract',
  path: '/extract',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComposerRoute = AuthenticatedComposerRouteImport.update({
  id: '/composer',
  path: '/composer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommentsRoute = AuthenticatedCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicDriveSplatRoute = ApiPublicDriveSplatRouteImport.update({
  id: '/api/public/drive/$',
  path: '/api/public/drive/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronSchedulerRoute = ApiPublicCronSchedulerRouteImport.update({
  id: '/api/public/cron/scheduler',
  path: '/api/public/cron/scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronRefreshTokensRoute =
  ApiPublicCronRefreshTokensRouteImport.update({
    id: '/api/public/cron/refresh-tokens',
    path: '/api/public/cron/refresh-tokens',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronCaptureInsightsRoute =
  ApiPublicCronCaptureInsightsRouteImport.update({
    id: '/api/public/cron/capture-insights',
    path: '/api/public/cron/capture-insights',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/comments': typeof AuthenticatedCommentsRoute
  '/composer': typeof AuthenticatedComposerRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/extract': typeof AuthenticatedExtractRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/pages': typeof AuthenticatedPagesRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sheets': typeof AuthenticatedSheetsRoute
  '/api/public/cron/capture-insights': typeof ApiPublicCronCaptureInsightsRoute
  '/api/public/cron/refresh-tokens': typeof ApiPublicCronRefreshTokensRoute
  '/api/public/cron/scheduler': typeof ApiPublicCronSchedulerRoute
  '/api/public/drive/$': typeof ApiPublicDriveSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/comments': typeof AuthenticatedCommentsRoute
  '/composer': typeof AuthenticatedComposerRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/extract': typeof AuthenticatedExtractRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/pages': typeof AuthenticatedPagesRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sheets': typeof AuthenticatedSheetsRoute
  '/api/public/cron/capture-insights': typeof ApiPublicCronCaptureInsightsRoute
  '/api/public/cron/refresh-tokens': typeof ApiPublicCronRefreshTokensRoute
  '/api/public/cron/scheduler': typeof ApiPublicCronSchedulerRoute
  '/api/public/drive/$': typeof ApiPublicDriveSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/comments': typeof AuthenticatedCommentsRoute
  '/_authenticated/composer': typeof AuthenticatedComposerRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/extract': typeof AuthenticatedExtractRoute
  '/_authenticated/groups': typeof AuthenticatedGroupsRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/pages': typeof AuthenticatedPagesRoute
  '/_authenticated/queue': typeof AuthenticatedQueueRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/sheets': typeof AuthenticatedSheetsRoute
  '/api/public/cron/capture-insights': typeof ApiPublicCronCaptureInsightsRoute
  '/api/public/cron/refresh-tokens': typeof ApiPublicCronRefreshTokensRoute
  '/api/public/cron/scheduler': typeof ApiPublicCronSchedulerRoute
  '/api/public/drive/$': typeof ApiPublicDriveSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/comments'
    | '/composer'
    | '/dashboard'
    | '/extract'
    | '/groups'
    | '/logs'
    | '/pages'
    | '/queue'
    | '/settings'
    | '/sheets'
    | '/api/public/cron/capture-insights'
    | '/api/public/cron/refresh-tokens'
    | '/api/public/cron/scheduler'
    | '/api/public/drive/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/comments'
    | '/composer'
    | '/dashboard'
    | '/extract'
    | '/groups'
    | '/logs'
    | '/pages'
    | '/queue'
    | '/settings'
    | '/sheets'
    | '/api/public/cron/capture-insights'
    | '/api/public/cron/refresh-tokens'
    | '/api/public/cron/scheduler'
    | '/api/public/drive/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/comments'
    | '/_authenticated/composer'
    | '/_authenticated/dashboard'
    | '/_authenticated/extract'
    | '/_authenticated/groups'
    | '/_authenticated/logs'
    | '/_authenticated/pages'
    | '/_authenticated/queue'
    | '/_authenticated/settings'
    | '/_authenticated/sheets'
    | '/api/public/cron/capture-insights'
    | '/api/public/cron/refresh-tokens'
    | '/api/public/cron/scheduler'
    | '/api/public/drive/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicCronCaptureInsightsRoute: typeof ApiPublicCronCaptureInsightsRoute
  ApiPublicCronRefreshTokensRoute: typeof ApiPublicCronRefreshTokensRoute
  ApiPublicCronSchedulerRoute: typeof ApiPublicCronSchedulerRoute
  ApiPublicDriveSplatRoute: typeof ApiPublicDriveSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sheets': {
      id: '/_authenticated/sheets'
      path: '/sheets'
      fullPath: '/sheets'
      preLoaderRoute: typeof AuthenticatedSheetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/queue': {
      id: '/_authenticated/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof AuthenticatedQueueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pages': {
      id: '/_authenticated/pages'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof AuthenticatedPagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups': {
      id: '/_authenticated/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/extract': {
      id: '/_authenticated/extract'
      path: '/extract'
      fullPath: '/extract'
      preLoaderRoute: typeof AuthenticatedExtractRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/composer': {
      id: '/_authenticated/composer'
      path: '/composer'
      fullPath: '/composer'
      preLoaderRoute: typeof AuthenticatedComposerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comments': {
      id: '/_authenticated/comments'
      path: '/comments'
      fullPath: '/comments'
      preLoaderRoute: typeof AuthenticatedCommentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/drive/$': {
      id: '/api/public/drive/$'
      path: '/api/public/drive/$'
      fullPath: '/api/public/drive/$'
      preLoaderRoute: typeof ApiPublicDriveSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/scheduler': {
      id: '/api/public/cron/scheduler'
      path: '/api/public/cron/scheduler'
      fullPath: '/api/public/cron/scheduler'
      preLoaderRoute: typeof ApiPublicCronSchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/refresh-tokens': {
      id: '/api/public/cron/refresh-tokens'
      path: '/api/public/cron/refresh-tokens'
      fullPath: '/api/public/cron/refresh-tokens'
      preLoaderRoute: typeof ApiPublicCronRefreshTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/capture-insights': {
      id: '/api/public/cron/capture-insights'
      path: '/api/public/cron/capture-insights'
      fullPath: '/api/public/cron/capture-insights'
      preLoaderRoute: typeof ApiPublicCronCaptureInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCommentsRoute: typeof AuthenticatedCommentsRoute
  AuthenticatedComposerRoute: typeof AuthenticatedComposerRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExtractRoute: typeof AuthenticatedExtractRoute
  AuthenticatedGroupsRoute: typeof AuthenticatedGroupsRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedPagesRoute: typeof AuthenticatedPagesRoute
  AuthenticatedQueueRoute: typeof AuthenticatedQueueRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSheetsRoute: typeof AuthenticatedSheetsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCommentsRoute: AuthenticatedCommentsRoute,
  AuthenticatedComposerRoute: AuthenticatedComposerRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExtractRoute: AuthenticatedExtractRoute,
  AuthenticatedGroupsRoute: AuthenticatedGroupsRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedPagesRoute: AuthenticatedPagesRoute,
  AuthenticatedQueueRoute: AuthenticatedQueueRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSheetsRoute: AuthenticatedSheetsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicCronCaptureInsightsRoute: ApiPublicCronCaptureInsightsRoute,
  ApiPublicCronRefreshTokensRoute: ApiPublicCronRefreshTokensRoute,
  ApiPublicCronSchedulerRoute: ApiPublicCronSchedulerRoute,
  ApiPublicDriveSplatRoute: ApiPublicDriveSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
